"""update_setting_key_unique

Revision ID: 801112c7f902
Revises: 8d9dec8dc849
Create Date: 2026-06-26 21:22:29.727078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '801112c7f902'
down_revision: Union[str, Sequence[str], None] = '8d9dec8dc849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_setting_group_key'), 'setting', type_='unique')
    op.create_unique_constraint(None, 'setting', ['key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'setting', type_='unique')
    op.create_unique_constraint(op.f('uq_setting_group_key'), 'setting', ['group_id', 'key'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
