"""add_product_desc

Revision ID: 59a709997d05
Revises: d70a00c4c41d
Create Date: 2026-07-18 21:43:38.412479

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "59a709997d05"
down_revision: Union[str, Sequence[str], None] = "d70a00c4c41d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('product', sa.Column('description', sa.Text(), nullable=False))
    op.add_column(
        "product",
        sa.Column("description", sa.Text(), server_default="", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "description")
    # ### end Alembic commands ###
