"""delete_product_desc

Revision ID: d70a00c4c41d
Revises: ae615fe3776d
Create Date: 2026-07-18 21:42:41.548241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd70a00c4c41d'
down_revision: Union[str, Sequence[str], None] = 'ae615fe3776d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
