/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AsideCard: typeof import('./../src/components/asideCard/index.vue')['default']
    AsideFn: typeof import('./../src/components/asideFn/index.vue')['default']
    AsideGroup: typeof import('./../src/components/asideGroup/index.vue')['default']
    AvatarName: typeof import('./../src/components/avatarName/index.vue')['default']
    ChatItem: typeof import('./../src/components/chatItem/index.vue')['default']
    ChatRoom: typeof import('./../src/components/chatRoom/index.vue')['default']
    CheckoutRow: typeof import('./../src/components/checkoutRow/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FriendRequest: typeof import('./../src/components/friendRequest/index.vue')['default']
    MyDialog: typeof import('./../src/components/myDialog/index.vue')['default']
    MyIcon: typeof import('./../src/components/myIcon/index.vue')['default']
    PersonInfo: typeof import('./../src/components/personInfo/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SendMsg: typeof import('./../src/components/sendMsg/index.vue')['default']
    UploadAvatar: typeof import('./../src/components/uploadAvatar/index.vue')['default']
    UserContextMenu: typeof import('./../src/components/userContextMenu/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
