apiVersion: v1
kind: Service
metadata:
  name: duyi-service
  labels:
    app: duyi-service
spec:
  type: ClusterIP
  selector:
    app: duyi-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
